spring:
  datasource:
    url: jdbc:mysql://192.168.121.137:3306/jdbc
    username: root
    password: nielong
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
#     更新或者创建数据表结构
      ddl-auto: update
#    控制台显示SQL
    show-sql: true
